<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\StaffSharp.Audio\StaffSharp.Audio.csproj" />
		<ProjectReference Include="..\StaffSharp.Core\StaffSharp.Core.csproj" />
		<ProjectReference Include="..\StaffSharp.Abc\StaffSharp.Abc.csproj" />
		<ProjectReference Include="..\StaffSharp.Midi\StaffSharp.Midi.csproj" />
		<ProjectReference Include="..\StaffSharp.Svg\StaffSharp.Svg.csproj" />
		<ProjectReference Include="..\StaffSharp.MusicXml\StaffSharp.MusicXml.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Spectre.Console" />
		<PackageReference Include="System.CommandLine" />
	</ItemGroup>

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

</Project>
