<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StaffSharp.Core\StaffSharp.Core.csproj" />
    <ProjectReference Include="..\StaffSharp.Audio\StaffSharp.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="MathNet.Numerics" />
    <PackageReference Include="System.Numerics.Tensors" />
  </ItemGroup>

</Project>
