<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>StaffSharp.Json</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StaffSharp.Core\StaffSharp.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Serialization\" />
  </ItemGroup>
</Project>
